# --- CONEXIÓN A SUPABASE (Connection Pooler) ---
spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bnaqxitmvgmspufbkpvt
spring.datasource.password=Li9GeOVJ7gcUkKxu
spring.datasource.driver-class-name=org.postgresql.Driver

# --- HIBERNATE / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=auth

# --- HIKARI CONNECTION POOL ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=SupabaseHikariCP

# --- SUPABASE AUTH ---
supabase.url=https://bnaqxitmvgmspufbkpvt.supabase.co
supabase.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuYXF4aXRtdmdtc3B1ZmJrcHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU0MTYwODgsImV4cCI6MjEwMDk5MjA4OH0.YwM5uznK1LMARZMkI42pQkeXN5N7UE2t04JhyPgxW-U

# --- VAADIN ---
server.port=${PORT:8080}
logging.level.org.atmosphere=warn
vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.application