# .devcontainer/docker-compose.yml
version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db # Esto permite que compartan la red fácilmente

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: logicore_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: