spring.application.name=logicore

spring.datasource.url=jdbc:postgresql://db:5432/logicore_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración MinIO (Object Storage)
minio.url=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadminpassword
minio.bucket-name=logicore-files

# Propiedades personalizadas para JWT
jwt.secret=MiClaveSecretaSuperSeguraDe32CaracteresMinimo!!!
jwt.expiration=86400000